---
all:
  hosts:
    chromebit:
      ansible_user: user
      ansible_host: chromebit.local
      ansible_become_method: doas
      ansible_become_pass: "{{ lookup('gopass', 'password/linux/user') }}"
    void-live:
      ansible_user: anon
      ansible_ssh_pass: voidlinux
      ansible_host: 192.168.123.181
      ansible_become_pass: "{{ lookup('gopass', 'password/linux/user') }}"
    surface-void:
      ansible_user: zxc
      ansible_host: surface-void.local
      ansible_become_pass: "{{ lookup('gopass', 'password/linux/user') }}"
windows:
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
  hosts:
    nuc:
      ansible_host: nuc.local
      my_hostname: nuc
    bed:
      ansible_host: bed.local
      my_hostname: bed
wsl:
  vars:
    ansible_connection: community.general.wsl
    ansible_user: user
  hosts:
    nuc-windows-wsl-debian:
      ansible_host: nuc.local
      wsl_distribution: debian
      wsl_user: root
    nuc-windows-wsl-arch:
      ansible_host: nuc.local
      wsl_distribution: archlinux
      wsl_user: root
termux:
  vars:
    ansible_ssh_port: 8022
  hosts:
    note20:
      ansible_host: 192.168.123.232
      ansible_user: u0_a644
work:
  hosts:
    test:
      ansible_host: 192.168.123.123
      ansible_user: uos
      ansible_become_pass: uos
